### ISSUE TITLE
nesper version

### ISSUE THREAD

**Issue by meirb** [espertechinc/nesper#1]
is the nesper 5.2 version is feature equivalent to the esper 5.2?
we have a big .net enterprise product  and we are considering both nesper and esper , as a .net company nesper will be easier for us to integrate but we noticed it does not have a big user base, is the support for the product is planed to be continued? are versions going to be continue to be correlated with esper?

**Comment by bernhardttom2** [comment]
> > is the nesper 5.2 version is feature equivalent to the esper 5.2?
> > yes
> > 
> > is the support for the product is planed to be continued? 
> > yes NEsper is commercially supported by EsperTech.
> > 
> > are versions going to be continue to be correlated with esper? 
> > yes
