### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by DixonDs** [espertechinc/nesper#10]
Any plans to migrate to .Net Core?

**Comment by ajaxx** [comment]
Just need people to test it out on .NET core, but yes it's in the plans.

**Comment by fcabrera23** [comment]
News with .net core version? Will definitely try it. Thanks

**Comment by ajaxx** [comment]
Definitely going to add tests in 6.0 to test with .NET core!

On Mon, Jun 26, 2017 at 8:47 PM, Francisco Cabrera <notifications@github.com

**Comment by fcabrera23** [comment]
Thanks, but is now available to install it by nuget?

**Comment by ajaxx** [comment]
The 6.0.1 has been an enormous refactor due to the changes in the Esper codebase.  You can see almost all of the code on the 6.0.1 branch at the moment.  And no, I haven't pushed it to nuget.  Once I've addressed all issues in the unit tests it will go out.

**Comment by wegged** [comment]
Also would like to know when the .net core version would become available on nuget?

**Comment by ajaxx** [comment]
I'm working on it.  There are some issues with a few of the underlying libraries that are used.  XLR8.CGLib is mine, so I've worked around what it does already.  Some of the others like Castle have not been as easy to migrate, but I should have something soon.  Also, you probably noticed the NEsper.Core package that now lives under the directory.  You can track that since I'm keeping .NET core specific features isolated there until I understand how it will affect those using .NET framework.

**Comment by mingboq** [comment]
Any updates on this?

**Comment by ajaxx** [comment]
I've been working on this.  With visual studio 2017, projects can be multitarget.  However, beyond just updating to 2017, there are some things that don't port over well to .NET core and we've had to adjust the container model to allow for factories for many of these objects... thread local manager, locks, etc.  I've got all of this written, but I'm going through all of the tests to make sure it's good.  It's definitely coming as part of 6.1.0 though.

**Comment by ajaxx** [comment]
You all will be happy to know that I've begun testing on 6.1.0 and it is a multitarget solution with specific targets for net46, net471, and netstandard2.0.  I'd appreciate any testing that you guys might want to help with.

**Comment by ajaxx** [comment]
Lots of work had to go into this but 6.1.0 is multitarget.  The new packages created from this release should target netstandard 2.0 which means you can now use it with your .net core instances.

**Comment by fcabrera23** [comment]
Thanks @ajaxx , I’m trying to get it working but still having some problems

**Comment by ajaxx** [comment]
Can you provide some examples of what's not working for you?

**Comment by ajaxx** [comment]
I've verified that we're building all packages against .netcoreapp3.1.
I've verified that the test suite (excluding database tests) against .netcoreapp3.1.
