### ISSUE TITLE
Error validating expression: Failed to validate filter expression

### ISSUE THREAD

**Issue by megedsh** [espertechinc/nesper#12]
Filter error when when adding an event type with the Type AssemblyQualifiedName
i do not get this error when using the Type FullName

Tests attached - Test1 is OK, Test 2 gets the error
[NesperTests.cs.txt](https://github.com/espertechinc/nesper/files/676941/NesperTests.cs.txt)

**Comment by ajaxx** [comment]
What is the specific error that you receive.  I'm testing 5.5.0 and I've added a test similar to this to TestLegacyEvents and I'm not seeing the error.  Now I also had to change several points where we handle types and that may have corrected it but it would help to know the error.

**Comment by megedsh** [comment]
Sorry , attached exception . 
[NesperException.txt](https://github.com/espertechinc/nesper/files/721815/NesperException.txt)
If ill have time i will download, 5.5.0 and run the test.
