### ISSUE TITLE
Can not destroy/dispose a statement

### ISSUE THREAD

**Issue by agtokty** [espertechinc/nesper#13]
hi, 
I am getting this MissingMethodException during disposing a statement

`System.MissingMethodException: Method not found: 'Void Castle.Core.Internal.CollectionExtensions.ForEach(System.Collections.Generic.IEnumerable`1<!!0>, System.Action`1<!!0>)'.
   at com.espertech.esper.core.start.EPStatementDestroyCallbackList.Destroy()
   at com.espertech.esper.core.service.StatementLifecycleSvcImpl.DestroyInternal(EPStatementDesc desc)
   at com.espertech.esper.core.service.StatementLifecycleSvcImpl.Dispose(Int32 statementId)
   at com.espertech.esper.core.service.EPStatementImpl.Dispose() in  Program.cs:line 171`

I also tried to remove listeners and stop statement first, but I got the same error again.

```
epService.EPAdministrator.GetStatement("test").RemoveAllEventHandlers();
epService.EPAdministrator.GetStatement("test").Stop();
epService.EPAdministrator.GetStatement("test").Dispose();
```
Is this about Castle.Core version ?

Here is  packages.config of project
[https://gist.github.com/agtokty/4bef3fed5251ceb98128fa524ada7f7a](https://gist.github.com/agtokty/4bef3fed5251ceb98128fa524ada7f7a)

**Comment by ajaxx** [comment]
Looks Castle specific, but I'll add a test for this in 6.0.  Will update once that's done.

**Comment by ajaxx** [comment]
There were several changes including some that affected Castle for this release.  I will be putting together a separate test for this (6.0.1 had a lot of unrelated changes).

**Comment by ajaxx** [comment]
Want to check this again with 6.1.0 since there was a heavy rewrite of many areas.
