### ISSUE TITLE
Setting internal timer as 'false'

### ISSUE THREAD

**Issue by 18310249** [espertechinc/nesper#14]
I am trying to set the '.setInternalTimerEnabled(false)' property. I am unable to change the Configuration like shown in reference: 

> Configuration config = new Configuration();
>   config.getEngineDefaults().getThreading().setInternalTimerEnabled(false);

I found the following instructions,  but I am unsure about how to implement it:

> com.espertech.esper.util.EsperSectionHandler is provided to read Esper configuration from standard .NET configuration. It must be added as a configSection in order to be used.

**Comment by ajaxx** [comment]
In NEsper, the configuration uses properties instead of setters.  You most
likely want the following:

configuration.EngineDefaults.ThreadingConfig.IsInternalTimerEnabled = false;
