### ISSUE TITLE
NullReferenceException in Ctor SingleRowMethodExpression(String method, Object[] parameters)

### ISSUE THREAD

**Issue by pa-hobe** [espertechinc/nesper#15]
The constructor `com.espertech.esper.client.soda.SingleRowMethodExpression..ctor(String method, Object[] parameters)` throws a `System.NullReferenceException` because `_chain` is not initialized in the constructor and `_chain.Add(...)` fails.

**Comment by ajaxx** [comment]
Do you have an example that will create the failure?  Something that I can build a test case around would be helpful.

**Comment by pa-hobe** [comment]
A minimal program for triggering the exception:

```
using com.espertech.esper.client.soda;

internal class Program
{
    private static void Main(string[] args)
    {
        var dummy = new SingleRowMethodExpression("method", new object[0]);
    }
}
```
The definition of the function in `SingleRowMethodExpression.cs` is:

```
19    public class SingleRowMethodExpression : ExpressionBase
20    {
21        private readonly IList<DotExpressionItem> _chain;
22
23        /// <summary>Ctor. </summary>
24        /// <param name="method">method name</param>
25        /// <param name="parameters">an optiona array of parameters</param>
26        public SingleRowMethodExpression(String method, Object[] parameters)
27        {
28            List<Expression> parameterList = new List<Expression>();
29            for (int i = 0; i < parameters.Length; i++)
30            {
31                if (parameters[i] is Expression)
32                {
33                    parameterList.Add((Expression)parameters[i]);
34                }
35                else
36                {
37                    parameterList.Add(new ConstantExpression(parameters[i]));
38                }
39            }
40            _chain.Add(new DotExpressionItem(method, parameterList, false));
41        }
```

The constructor starting at line 26 calls `_chain.Add(...)` in line 40, but `_chain`, declared in line 21, is still `null`. This is fixed by inserting the following line before line 40:

`_chain = new List<DotExpressionItem>();
`

BTW, there is a typo in the comment in line 25:
    `an optiona array` -> `an optional array`
