### ISSUE TITLE
Empty array is not possible

### ISSUE THREAD

**Issue by pa-hobe** [espertechinc/nesper#19]
An empty array is possible according to the documentation for Esper 6.0.1:

> **9.5. Array Definition Operator**
> [...]
> `{ [expression [,expression...]] }`

However, the definition in the grammar file `NEsper/grammar/EsperEPL2Grammar.g4`

`elementValueArrayEnum : '{' (elementValueEnum (',' elementValueEnum)*)? (',')? '}';`

requires a mandatory element.

**Comment by ajaxx** [comment]
Good point.  I'll bring this up with the Esper team since the two projects share the same grammar - they would both have the same issue.
