### ISSUE TITLE
System.String

### ISSUE THREAD

**Issue by vermeulenjp** [espertechinc/nesper#2]
Hi there, I'm busy creating an large scale CEP engine for my organization. We created a C# mapping, Dictionary<string,object> where the properties are like the following amount, **System.Double** ; registeredon, **System.DateTime**, firstname, **System.String**. Problem is that the process of _AddEventType_ fails. the failure is here:

**TypeHelper.cs**
 case "string":
                    return typeof(string);
_line: 1361_

You may need to add 
case "system.string":

I did this in the code locally and the AddEventType process succeeded.

_thank-you_

**Comment by ajaxx** [comment]
Thanks, this has been added to NEsper 5.3.
