### ISSUE TITLE
Measure data types

### ISSUE THREAD

**Issue by obratim** [espertechinc/nesper#20]
After adding event type using
`void AddEventType(string eventTypeName, IDictionary<string, object> typeMap, string[] superTypes);`
overload, I can send events, represented as Dictionary<string, object>, using overload
`void SendEvent(IDictionary<string, object> map, string mapEventTypeName);`
I can see, it is not forbbidden to add event type with integer/float-point values, but send events with strings as values in dictionary. Registred statements works correct, comparisons and arithmetical operations with integer and float-point numbers work correct, as if NEsper converts string values to corresponding type. But if I add bitwise operation into statement, this statements stops returning any results.
Also, when I subscrie to statement and look at NewEvents in the debugger, I see strings as original values and int or double as result of arithmetical operation.
Am I doing it wrong ?

**Comment by ajaxx** [comment]
Do you have a bit of sample code we can look at?

**Comment by obratim** [comment]
[CEP.zip](https://github.com/espertechinc/nesper/files/2255073/CEP.zip)
Here is my sample project.
You can see, I send strings as values to NEsper, then results are strings for original fields and numbers for results of arithmetic operations.

**Comment by ajaxx** [comment]
Thanks, I'll take a look at it.

**Comment by ajaxx** [comment]
Can you retest this against .NEsper 8.5.0.
