### ISSUE TITLE
Subqueries in FROM clause

### ISSUE THREAD

**Issue by jonimoreira** [espertechinc/nesper#21]
Hi,

Does NESPER support subqueries within FROM clauses? I'm trying to follow the FROM documentation [1] (should be similar to SQL):
"The subquery_expr defines a subquery or nested EPL statement in parenthesis. A subquery is used to pre-filter event stream data seen by the outer EPL statement."

I'm getting a syntax error ("Incorrect syntax near '(' ") when I try to compose a simple query like this:
SELECT * FROM ( SELECT resultTime FROM Observation )

The "Simple and Correlated Subqueries" approach works but it is too limited - I can only access one event properties from a subquery, but I need to access multiple properties. 

I want to relate three queries, such as:
SELECT *
FROM (SubQuery1) as X1,  (SubQuery2) as X2, (SubQuery3) as X3, 
WHERE X1.id = X2.id and X2.id = X3.id and X1.propA > 10

In addition, I'd like to be able to relate temporally these subqueries, e.g. an X1 followed by X2 within 10 seconds. Do I need to use the MATCHING clause or is it possible to do that with FROM? One of my goals is to be able to represent each Allen operator [2] in EPL statements. 

Thanks.

Joao

[1] https://docs.oracle.com/cd/E13157_01/wlevs/docs30/epl_guide/clauses.html#wp1016544
[2] https://en.wikipedia.org/wiki/Allen%27s_interval_algebra

**Comment by bernhardttom** [comment]
There is no support for subqueries in the from-clause. Allen is already part of EPL. The from-clause has streams and subqueries go against tables thus streaming semantics don't allow subqueries in the from-clause.

**Comment by jonimoreira** [comment]
Hi,

Just for information for other readers, the EPL documentation in Oracle's website is incorrect: 

> The subquery_expr defines a subquery or nested EPL statement in parenthesis. A subquery is used to pre-filter event stream data seen by the outer EPL statement. For example, the following query would restrict the data seen by the outer EPL statement to only StockTick events coming from a Reuters feed.
  SELECT stockSymbol, AVG(price)
  FROM (SELECT * FROM StockTick WHERE feedName = 'Reuters' ) 
  RETAIN 1 MINUTE PARTITION BY stockSymbol
  GROUP BY stockSymbol

https://docs.oracle.com/cd/E13157_01/wlevs/docs30/epl_guide/clauses.html#wp1016544

The link to the up-to-date documentation of NESPER can be found in the releases page and is always referent to an ESPER version:
http://www.espertech.com/esper/nesper-for-net-documentation/

For version 6.0.x:
http://esper.espertech.com/release-6.0.1/esper-reference/html/epl_clauses.html#epl-subqueries

Joao
