### ISSUE TITLE
[BUG REPORT] SQL metadata retrieval fails while processing output types for query

### ISSUE THREAD

**Issue by TimeWanderer** [espertechinc/nesper#29]
While creating HistoricalEventViewableDatabaseFactory object, OutputTypes property expects `IDictionary<string, DBOutputTypeDesc>`, however HistoricalEventViewableDatabaseForge generates a function that returns `IDictionary<object, object>`.

It causes an error while compiling the generated code for statements with external SQL db access:

`error CS0266: Cannot implicitly convert type 'System.Collections.Generic.IDictionary<object, object>' to 'System.Collections.Generic.IDictionary<string, com.espertech.esper.common.@internal.epl.historical.database.core.DBOutputTypeDesc>'.
`

Replacing IDictionary template parameters in HistoricalEventViewableDatabaseForge.MakeOutputTypes fixes the issue.

**Comment by TimeWanderer** [comment]
[RDB_Test.zip](https://github.com/espertechinc/nesper/files/6546306/RDB_Test.zip)
You can use this to reproduce the issue.

**Comment by ajaxx** [comment]
I have a PR for 8.5.2 that fixes the compilation error in this area.
