### ISSUE TITLE
NullReferenceException when casting property to int  (regression from 4.8 and 5.0.1)

### ISSUE THREAD

**Issue by rgl** [espertechinc/nesper#6]
The following EPL does not work on NEsper above v4.8 (**NB** it also works with 5.0.1, the only other 5.x version I tested with):

``` sql
select cast(cast(Properties('value'), string), int) as Value
from PropertiesEvent
```

The `PropertiesEvent` is defined as:

``` csharp
public class PropertiesEvent
{
    public IDictionary<string, object> Properties { get; set; }
}
```

Check the test at [EplTest.cs:CastPropertyToIntRegression](https://github.com/rgl/UseNesper2/blob/master/csharp/UseNEsper2/EplTests.cs). If you checkout the [nesper-4.8 branch](https://github.com/rgl/UseNesper2/blob/nesper-4.8/UseNEsper2/EplTests.cs) (same code, only the nesper libraries are changed) it works fine.

Can you reproduce the problem?

I'm using normal .NET 4.6 on Windows.

**Comment by ajaxx** [comment]
Fixed in 5.5.0 - there's actually a nested cast problem that was catching it and turning it into a constant.
