### ISSUE TITLE
Method invocation fails

### ISSUE THREAD

**Issue by malichishti** [espertechinc/nesper#7]
**Query**
`SELECT * 
FROM method:handler.getContext()`

**Configuration:**
`cepConfig.AddVariable<Handler>("handler", new Handler());`

```
public class Handler
{
    public Dictionary<string, object> getContextMetadata()
    {
        return Metadata.get();
    }

    public IEnumerable<IDictionary<string, Object>> getContext()
    {
        foreach(var data in Data.get())
              yield return data;
    }
}
```

**Error:**
Unexpected exception starting statement: Could not find getter method for method invocation, expected a method by name 'getContextMetadata' accepting no parameters [SELECT \* \nFROM method:handler.getContext()]

**Comment by ajaxx** [comment]
The xxxMetadata method it's looking for must return IDictionary<string, object>, not Dictionary.  It's just a concrete class vs interface problem.
