### ISSUE TITLE
Non safe Assembly.GetTypes() call in DiscoverEngines method

### ISSUE THREAD

**Issue by megedsh** [espertechinc/nesper#9]
In ScriptingServiceImpl.cs.
Function DiscoverEngines, iterates on all Current AppDomain  Loaded assemblies.
For each assembly, a GetTypes() function is called. 

In my application, this is unsafe because, you try to load types from assemblies that Nesper has no interface with. For example, my application crashes because missing DevExpress dlls, when trying to init a nesper instance.

You should either make the function safe (attached) or only supply an interface for searching engines on specific assemblies.

[ScriptingServiceImpl.txt](https://github.com/espertechinc/nesper/files/577645/ScriptingServiceImpl.txt)

**Comment by ajaxx** [comment]
We've applied your patch to 5.5.0.
